---
- hosts: ndfc_servers
  gather_facts: false
  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        file: ../data/01_add-devices.yaml
        name: switch_data
        
    - name: Add devices via REST call to NDFC
      cisco.dcnm.dcnm_rest:
        method: POST
        path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/pod05/inventory/discover?setAndUseDiscoveryCredForLan=false
        json_data: "{{ item.inventory | from_yaml | to_json }}"
      with_items: "{{ switch_data.fabric_data.switches }}"